### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by skinnybrit51** [jedmao/codepainter#43]
Does npm install fail for anyone else? Getting an issue around editorconfig saying the file can not be found.

npm version 2.11.3
node version 0.12.7

**Comment by jedmao** [comment]
Works fine for me.

**Comment by skinnybrit51** [comment]
With the same version numbers of npm and node? I have no issues installing other npm libraries.

**Comment by jedmao** [comment]
Yes. I have the exact same Node and npm versions. Try `npm cache clean`.
